name: Test autify-datadog-action

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Run autify-datadog-action
        uses: chaspy/autify-datadog-action@main
        with:
          autify_personal_access_token: ${{ secrets.AUTIFY_PERSONAL_ACCESS_TOKEN }}
          autify_project_id: ${{ secrets.AUTIFY_PROJECT_ID}}
          datadog_api_key: ${{ secrets.DATADOG_API_KEY}}
